// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlrvtrunhznagpjxugfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFscnZ0cnVuaHpuYWdwanh1Z2ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDM3ODQsImV4cCI6MjA2MTE3OTc4NH0.SQoVNfWzQMkzv2WhdbB_BUvtGjLZjI0gtyL6-b1l4FE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);